#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
CC := $(TOOLCHAIN_ROOT)/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-gcc.exe
CXX := $(TOOLCHAIN_ROOT)/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-g++.exe
LD := $(CXX)
AR := $(TOOLCHAIN_ROOT)/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-ar.exe
OBJCOPY := $(TOOLCHAIN_ROOT)/bin/arm-poky-linux-gnueabi/arm-poky-linux-gnueabi-objcopy.exe

#Additional flags
PREPROCESSOR_MACROS := DEBUG=1
INCLUDE_DIRS := 
LIBRARY_DIRS := C:\public\SysGCC\new\sysroots\cortexa9hf-neon-poky-linux-gnueabi\usr\lib
LIBRARY_NAMES := paho-mqtt3a paho-mqtt3c paho-mqttpp3
ADDITIONAL_LINKER_INPUTS := 
MACOS_FRAMEWORKS := 
LINUX_PACKAGES := 

CFLAGS := -ggdb -ffunction-sections -O0
CXXFLAGS := -ggdb -ffunction-sections -O0
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := -march=armv7-a -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 --sysroot=C:\public\SysGCC\new\sysroots\cortexa9hf-neon-poky-linux-gnueabi
LINKER_SCRIPT := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
USE_DEL_TO_CLEAN := 1
CP_NOT_AVAILABLE := 1
IS_LINUX_PROJECT := 1
